{{- range $index, $node := ($.Values.hedera.nodes) }}
{{- $grafanaAlloy := ($node.sidecars).grafanaAlloy | default $.Values.defaults.sidecars.grafanaAlloy }}
{{- if $grafanaAlloy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-cm-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "solo.testLabels" $ | nindent 4 }}
data:
  config.alloy: |
  {{- $params := dict "" "" -}}
  {{- $_ignore := set $params "alloyDefaults" $grafanaAlloy -}}
  {{- $_ignore = set $params "Template" $.Template -}}
  {{- $_ignore = set $params "environment_name" $.Release.Namespace -}}
  {{- $_ignore = set $params "alloy_node_id" $index -}}
  {{- tpl ( $.Files.Get "config-files/alloy-config.alloy" ) $params | nindent 4 }}
---
{{- end }}
{{- end }}
