{{- if .Values.envoyProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-proxy-cm-{{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.global.namespaceOverride }}
  labels:
    {{- include "solo.testLabels" . | nindent 4 }}
data:
  envoy.yaml: |
    {{- tpl (.Files.Get "config-files/envoy.yaml") (dict "nodeConfig" .Values "namespace" (default .Release.Namespace .Values.global.namespaceOverride) "Template" .Template) | nindent 4 }}
{{- end }}
