name: Bug Report
description: File a bug report
#title: "<Please write a short description of what didn't work for you here>"
labels: ["Bug", "Pending Triage"]
body:
  - type: input
    id: version
    attributes:
      label: Chart Version
      description: What version of Helm chart are you using?
      placeholder: 0.1.0
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe the expected behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what the expected behavior is.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Describe the bug
      description: Also tell us, what did happen?
      placeholder: A clear and concise description of what happened.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      render: markdown
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
