version: 3
output: prefixed

silent: false

tasks:
  "deploy:local": # deploy the chart locally for manual validation. to clean up run task cleanup:local
    cmds:
      - ./deploy_local.sh

  "cleanup:local":
    cmds:
      - kind delete cluster --name solo-charts-test