# SPDX-License-Identifier: Apache-2.0

{{- $name := "solo-shared-resources-passwords" -}}  # postgresl-ha doesn't support templated names
{{- $secret := lookup "v1" "Secret" (include "solo-shared-resources.namespace" .) $name | default dict -}}
{{- $passwords := $secret.data | default dict -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "solo-shared-resources.labels" . | nindent 4 }}
  name: {{ $name }}
  namespace: {{ include "solo-shared-resources.namespace" . }}
stringData:
  {{ if .Values.postgresql.enabled -}}
  password: {{ (get $passwords "password" | default "" | b64dec) | default (randAlphaNum 40) | quote }}
  POSTGRESQL_TIMEZONE: "UTC"
  {{ end -}}
