# SPDX-License-Identifier: Apache-2.0

global:
  namespaceOverride: ""
  security:
    allowInsecureImages: true

labels: {}

postgresql:
  enabled: true
  nameOverride: postgres
  persistence:
    size: 500Gi
  auth:
    existingSecret: solo-shared-resources-passwords
    secretKeys:
      adminPasswordKey: password
  primary:
    resources:
      limits:
        cpu: 1500m
        memory: 1000Mi
      requests:
        cpu: 250m
        memory: 500Mi

redis:
  auth:
    existingSecret: "{{ .Release.Name }}-redis"
    existingSecretPasswordKey: SPRING_DATA_REDIS_PASSWORD
    password: ""  # Randomly generated if left blank
  enabled: true
  host: "{{ .Release.Name }}-redis"
  kubectl:
    image:
      repository: rancher/kubectl
      tag: v1.33.4
  metrics:
    image:
      repository: bitnamilegacy/redis-exporter
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 25Mi
    serviceMonitor:
      enabled: true
  pdb:
    create: true
  port: 6379
  rbac:
    create: true
  replica:
    podAntiAffinityPreset: soft
    podSecurityContext:
      runAsGroup: 1001
      runAsUser: 1001
    replicaCount: 1
    resources:
      limits:
        cpu: 1500m
        memory: 2000Mi
      requests:
        cpu: 250m
        memory: 1000Mi
  sentinel:
    enabled: true
    masterSet: solo-master
    persistence:
      enabled: true
    readinessProbe:
      timeoutSeconds: 4
    resources:
      limits:
        cpu: 150m
        memory: 256Mi
      requests:
        cpu: 75m
        memory: 75Mi
  serviceAccount:
    create: true
